# Generated by Django 4.2.6 on 2023-10-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objeto', models.TextField()),
                ('edital', models.CharField(max_length=50)),
                ('numero_licitacao', models.IntegerField()),
                ('processo', models.CharField(max_length=50)),
                ('edital_online', models.CharField(max_length=50)),
                ('datas', models.CharField(max_length=200)),
                ('observacao', models.TextField()),
                ('unidade_licitante', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
